### ISSUE TITLE
sendPacket function not implemented in test project for Windows

### ISSUE THREAD

**Issue by tech-uday-mca** [intel/libdmclient#1]
Hi,

I was trying to use the libdmclient to work with funambol server for some test and i discover that for Windows, the sendPacket method is not properly implmented.

As expected, the sendPacket method in main.c must make a HTTP POST request to funambol server to send syncml data, the actual implementation is returning hard-coded value '503' as HTTP Error Code (which means service unavailable).

Here's the actual code that is inside sendPacket method in main.c:

long sendPacket(char \* type,
                dmclt_buffer_t \* packet,
                dmclt_buffer_t \* reply)
{
    long status = 503;

```
memset(reply, 0, sizeof(dmclt_buffer_t));

return status;
```

}

Please provide an fix for this bug

**Comment by BertrandAygon** [comment]
Hi,

We will look at this asap.

Bertrand

**Comment by BertrandAygon** [comment]
Hi,

Thanks to Isabelle Magi, I pushed a patches that enable sendPacket function.

A lib CURL is needed.

You can download this one: http://curl.haxx.se/latest.cgi?curl=win32-ssl-devel-msvc 

Copy/paste the folder include\curl\ from the zipped package into the VC folder of your Visual Studio installation.
Copy/paste the curllib.lib file from lib\Release\ of the zipped package into the VC/Lib folder of your Visual Studio installation.
In Visual Studio tool, right-click on Project -> Properties. Go to Configuration Properties -> Link editor -> Input.
In Other Dependencies section, enter the path to curllib.lib file: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\lib\curllib.lib
Last step is to copy/paste all .dll from the zipped file and to copy them in the \libdmclient\tests\windows\Debug folder of libdmclient project, near testdmclient.exe : curllib.dll, libeay32.dll, ssleay32.dll et openldap.dll

Thanks again to Isabelle.

Bertrand
