### ISSUE TITLE
Memory Leakage

### ISSUE THREAD

**Issue by syrykh** [intel/libdmclient#2]
Hi,

I've found a memory leakage in your great library.

When a "Tree discovery" command for Entire Tree is issued by Funambol server, the request will contain "." as a request URI. Then after a chain of functions, `momgr_get_value` _(momgr.c:635)_ function will be called. That function will find a plugin for "." node that is defined in _defaultroot.c_ file. Then `prv_get` _(defaultroot.c:69)_ function will be issued.

In this function memory is allocated by executing _(defaultroot.c:77)_:

``` C
nodeP->format = strdup("node");
```

But when returned to `momgr_get_value` function, this pointer will be re-allocated by the following line of code _(momgr.c:677)_:

``` C
// at this point nodeP->format is allready alocated by prv_get function
DMC_FAIL_NULL(nodeP->format, strdup("node"), OMADM_SYNCML_ERROR_DEVICE_FULL);
```

And this leads to a leakage because memory that is allocated by first `strdup` is not freed.

One of the possible solution is to check `nodeP->format` against NULL before making `strdup`.

```
if (!nodeP->format) {
  DMC_FAIL_NULL(nodeP->format, strdup("node"), OMADM_SYNCML_ERROR_DEVICE_FULL);
}
```

Please find some time to fix this issue. Thank you!
Warmest regards!

**Comment by dnav** [comment]
Hi,

Thank you for spotting this. It is fixed with commit 9d4e3e8f252ea6e70f9b0b5f8e1fc733852d8c17

Regards
