### ISSUE TITLE
Confirm license issue

### ISSUE THREAD

**Issue by steveyook** [intel/libdmclient#4]
Is libdmclient distributed  under under APACHEv2 ?
## But  homepage about this project (https://01.org/libdmclient/) say

Project Specifics
##  This is a small active open source project written in the C programming language and distributed under the LGPL open source license. Patches and requests are taken through GitHub.

But I can not find any evidence about LGPL license at source code.

Could anybody confirm which one is right? LGPL or APACHEv2 ?

**Comment by dnav** [comment]
Hi,
at first we planned to release libdmclient under a LGPL license. But we decided to use an APACHEv2 license.
So I confirm libdmclient is under APACHEv2.
I'll update the homepage. Thanks for spotting the mismatch.
